// flow-typed signature: c007a3edd26b93b117f0e6a205090e69
// flow-typed version: <<STUB>>/cogo-toast_v^3.2.1/flow_v0.104.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cogo-toast'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cogo-toast' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cogo-toast/dist/index.es' {
  declare module.exports: any;
}

declare module 'cogo-toast/dist' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cogo-toast/dist/index.es.js' {
  declare module.exports: $Exports<'cogo-toast/dist/index.es'>;
}
declare module 'cogo-toast/dist/index' {
  declare module.exports: $Exports<'cogo-toast/dist'>;
}
declare module 'cogo-toast/dist/index.js' {
  declare module.exports: $Exports<'cogo-toast/dist'>;
}
