// flow-typed signature: 3218a5bdc3d65fcdfa6edaa45c799136
// flow-typed version: <<STUB>>/@apollo/react-common_v^3.0.0/flow_v0.104.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@apollo/react-common'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@apollo/react-common' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@apollo/react-common/lib/context/ApolloConsumer' {
  declare module.exports: any;
}

declare module '@apollo/react-common/lib/context/ApolloContext' {
  declare module.exports: any;
}

declare module '@apollo/react-common/lib/context/ApolloProvider' {
  declare module.exports: any;
}

declare module '@apollo/react-common/lib' {
  declare module.exports: any;
}

declare module '@apollo/react-common/lib/parser/parser' {
  declare module.exports: any;
}

declare module '@apollo/react-common/lib/react-common.cjs' {
  declare module.exports: any;
}

declare module '@apollo/react-common/lib/react-common.cjs.min' {
  declare module.exports: any;
}

declare module '@apollo/react-common/lib/react-common.esm' {
  declare module.exports: any;
}

declare module '@apollo/react-common/lib/react-common.umd' {
  declare module.exports: any;
}

declare module '@apollo/react-common/lib/types/types' {
  declare module.exports: any;
}

// Filename aliases
declare module '@apollo/react-common/lib/context/ApolloConsumer.js' {
  declare module.exports: $Exports<
    '@apollo/react-common/lib/context/ApolloConsumer'
  >;
}
declare module '@apollo/react-common/lib/context/ApolloContext.js' {
  declare module.exports: $Exports<
    '@apollo/react-common/lib/context/ApolloContext'
  >;
}
declare module '@apollo/react-common/lib/context/ApolloProvider.js' {
  declare module.exports: $Exports<
    '@apollo/react-common/lib/context/ApolloProvider'
  >;
}
declare module '@apollo/react-common/lib/index' {
  declare module.exports: $Exports<'@apollo/react-common/lib'>;
}
declare module '@apollo/react-common/lib/index.js' {
  declare module.exports: $Exports<'@apollo/react-common/lib'>;
}
declare module '@apollo/react-common/lib/parser/parser.js' {
  declare module.exports: $Exports<'@apollo/react-common/lib/parser/parser'>;
}
declare module '@apollo/react-common/lib/react-common.cjs.js' {
  declare module.exports: $Exports<'@apollo/react-common/lib/react-common.cjs'>;
}
declare module '@apollo/react-common/lib/react-common.cjs.min.js' {
  declare module.exports: $Exports<
    '@apollo/react-common/lib/react-common.cjs.min'
  >;
}
declare module '@apollo/react-common/lib/react-common.esm.js' {
  declare module.exports: $Exports<'@apollo/react-common/lib/react-common.esm'>;
}
declare module '@apollo/react-common/lib/react-common.umd.js' {
  declare module.exports: $Exports<'@apollo/react-common/lib/react-common.umd'>;
}
declare module '@apollo/react-common/lib/types/types.js' {
  declare module.exports: $Exports<'@apollo/react-common/lib/types/types'>;
}
