// flow-typed signature: 5875484bccb5ff45c603a002191377bf
// flow-typed version: <<STUB>>/@apollo/react-testing_v^3.0.0/flow_v0.104.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@apollo/react-testing'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@apollo/react-testing' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@apollo/react-testing/lib' {
  declare module.exports: any;
}

declare module '@apollo/react-testing/lib/mocks/MockedProvider' {
  declare module.exports: any;
}

declare module '@apollo/react-testing/lib/mocks/mockLink' {
  declare module.exports: any;
}

declare module '@apollo/react-testing/lib/mocks/mockSubscriptionLink' {
  declare module.exports: any;
}

declare module '@apollo/react-testing/lib/mocks/types' {
  declare module.exports: any;
}

declare module '@apollo/react-testing/lib/react-testing.cjs' {
  declare module.exports: any;
}

declare module '@apollo/react-testing/lib/react-testing.cjs.min' {
  declare module.exports: any;
}

declare module '@apollo/react-testing/lib/react-testing.esm' {
  declare module.exports: any;
}

declare module '@apollo/react-testing/lib/react-testing.umd' {
  declare module.exports: any;
}

declare module '@apollo/react-testing/lib/utils/createClient' {
  declare module.exports: any;
}

declare module '@apollo/react-testing/lib/utils/stripSymbols' {
  declare module.exports: any;
}

declare module '@apollo/react-testing/lib/utils/wait' {
  declare module.exports: any;
}

// Filename aliases
declare module '@apollo/react-testing/lib/index' {
  declare module.exports: $Exports<'@apollo/react-testing/lib'>;
}
declare module '@apollo/react-testing/lib/index.js' {
  declare module.exports: $Exports<'@apollo/react-testing/lib'>;
}
declare module '@apollo/react-testing/lib/mocks/MockedProvider.js' {
  declare module.exports: $Exports<
    '@apollo/react-testing/lib/mocks/MockedProvider'
  >;
}
declare module '@apollo/react-testing/lib/mocks/mockLink.js' {
  declare module.exports: $Exports<'@apollo/react-testing/lib/mocks/mockLink'>;
}
declare module '@apollo/react-testing/lib/mocks/mockSubscriptionLink.js' {
  declare module.exports: $Exports<
    '@apollo/react-testing/lib/mocks/mockSubscriptionLink'
  >;
}
declare module '@apollo/react-testing/lib/mocks/types.js' {
  declare module.exports: $Exports<'@apollo/react-testing/lib/mocks/types'>;
}
declare module '@apollo/react-testing/lib/react-testing.cjs.js' {
  declare module.exports: $Exports<
    '@apollo/react-testing/lib/react-testing.cjs'
  >;
}
declare module '@apollo/react-testing/lib/react-testing.cjs.min.js' {
  declare module.exports: $Exports<
    '@apollo/react-testing/lib/react-testing.cjs.min'
  >;
}
declare module '@apollo/react-testing/lib/react-testing.esm.js' {
  declare module.exports: $Exports<
    '@apollo/react-testing/lib/react-testing.esm'
  >;
}
declare module '@apollo/react-testing/lib/react-testing.umd.js' {
  declare module.exports: $Exports<
    '@apollo/react-testing/lib/react-testing.umd'
  >;
}
declare module '@apollo/react-testing/lib/utils/createClient.js' {
  declare module.exports: $Exports<
    '@apollo/react-testing/lib/utils/createClient'
  >;
}
declare module '@apollo/react-testing/lib/utils/stripSymbols.js' {
  declare module.exports: $Exports<
    '@apollo/react-testing/lib/utils/stripSymbols'
  >;
}
declare module '@apollo/react-testing/lib/utils/wait.js' {
  declare module.exports: $Exports<'@apollo/react-testing/lib/utils/wait'>;
}
